os: linux
dist: jammy
sudo: true
language: c
version: ~> 1.0

cache:
  apt: true
  ccache: true

env:
  global: local=0 DB=testcpp CLEAR_TEXT=0

import: mariadb-corporation/connector-test-machine:common-build.yml@master

jobs:
  allow_failures:
    - env: srv=build
    - env: srv=xpand
    - env: srv=mysql v=5.7
    - env: srv=mysql v=8.0
    - env: srv=mariadb v=10.6
      os: windows
    - os: osx
    - os: linux
      arch: s390x
      dist: focal
    - env: srv=maxscale MAXSCALE_TEST_DISABLE=true
    - env: srv=xpand
#    - env: srv=skysql SKYSQL=true
#    - env: srv=skysql-ha SKYSQL_HA=true MAXSCALE_TEST_DISABLE=true
  include:
    - stage: Minimal
      env: srv=mariadb v=10.6 local=1
      name: "CS 10.6"
    - env: srv=mariadb-es v=10.6
      name: "ES 10.6"
      if: type = push AND fork = false

    - stage: Enterprise
      env: srv=mariadb-es v=10.4
      name: "ES 10.4"
    - env: srv=mariadb-es v=10.5
      name: "ES 10.5"
      #    - env: srv=mariadb v=10.6 local=1 BENCH=true
      #name: "benchmark"
    - env: srv=mariadb-es-test v=23.08
      name: "ES 23.08"
      if: type = push AND fork = false
    - env: srv=maxscale MAXSCALE_TEST_DISABLE=true
      name: "Maxscale"
#    - env: srv=skysql SKYSQL=true
#      name: "SkySQL"
#    - env: srv=skysql-ha SKYSQL_HA=true MAXSCALE_TEST_DISABLE=true
#      name: "SkySQL with replication"
    - env: srv=xpand
      name: "Xpand"

    - stage: Community
      env: srv=mariadb v=10.4
      os: windows
      language: shell
      name: "CS 10.4 - Windows"
    - env: srv=mariadb v=10.11 local=1
      name: "CS 10.11"
    - env: srv=mariadb v=10.5 local=1
      name: "CS 10.5"
    - env: srv=mariadb v=11.0 local=1
      name: "CS 11.0"
    - env: srv=mariadb v=11.1 local=1
      name: "CS 11.1"
    - env: srv=mariadb v=11.2 local=1
      name: "CS 11.2"
    - env: srv=mysql v=5.7
      name: "MySQL 5.7"
    - env: srv=mysql v=8.0
      name: "MySQL 8.0"
    - env: srv=build
      name: "CS build"
    - os: osx
      compiler: clang
      before_script:
        - brew install openssl
        - brew install libiodbc
    - os: linux
      arch: s390x
      dist: focal
      env: srv=mariadb v=10.11 local=1

script: ./travis.sh
